module.exports = function (sequelize, DataTypes) {
  return sequelize.define("survey23", {
    Q1A: DataTypes.INTEGER,
    Q1B: DataTypes.INTEGER,
    Q1C: DataTypes.INTEGER,
    Q1D: DataTypes.INTEGER,
    Q1E: DataTypes.INTEGER,
    Q1F: DataTypes.INTEGER,
    Q1G: DataTypes.INTEGER,
    Q1H: DataTypes.INTEGER,
    Q1I: DataTypes.INTEGER,
    Q1J: DataTypes.INTEGER,
    Q1K: DataTypes.INTEGER,
    Q2: DataTypes.STRING,
    Q3A: DataTypes.INTEGER,
    Q3B: DataTypes.INTEGER,
    Q3C: DataTypes.INTEGER,
    Q3D: DataTypes.INTEGER,
    Q3E: DataTypes.STRING,
    Q4: DataTypes.STRING,
    Q5: DataTypes.INTEGER,
    Q5A: DataTypes.STRING,
    Q6A: DataTypes.STRING,
    Q6B: DataTypes.STRING,
    Q6C: DataTypes.STRING,
    Q6D: DataTypes.STRING,
    Q7: DataTypes.STRING,
    Q8: DataTypes.STRING,
    Q9A: DataTypes.INTEGER,
    Q9B: DataTypes.INTEGER,
    Q9C: DataTypes.INTEGER,
    Q9D: DataTypes.INTEGER,
    Q10A: DataTypes.INTEGER,
    Q10B: DataTypes.INTEGER,
    Q10C: DataTypes.INTEGER,
    Q10D: DataTypes.INTEGER,
    Q10E: DataTypes.INTEGER,
    Q10F: DataTypes.INTEGER,
    Q10G: DataTypes.INTEGER,
    Q10H: DataTypes.INTEGER,
    Q11: DataTypes.INTEGER,
    Q12: DataTypes.INTEGER,
  });
};
